//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ankete
    {
        public ankete()
        {
            this.stavkes = new HashSet<stavke>();
        }
    
        public int Id_ankete { get; set; }
        public string naziv_ankete { get; set; }
    
        public virtual ICollection<stavke> stavkes { get; set; }
    }
}
