//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bioskopi
    {
        public int IdBioskopa { get; set; }
        public string NazivBioskopa { get; set; }
        public string UlicaBioskopa_ { get; set; }
        public int BrojUliceBioskopa { get; set; }
        public string GradBioskopa { get; set; }
        public string DrzavaBioskopa { get; set; }
        public string TelefonBioskopa { get; set; }
        public string EmailBioskopa { get; set; }
    }
}
