//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmovi
    {
        public int IdFilma { get; set; }
        public string NazivFilma { get; set; }
        public int IdBioskopa { get; set; }
        public string OpisFilma { get; set; }
        public int Ocena { get; set; }
        public System.DateTime DatumPostavljanja { get; set; }
        public string PutanjaDoSlike { get; set; }
        public string Zanrovi { get; set; }
        public string Korisnik { get; set; }
    }
}
