//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galerija
    {
        public int IdGalerije { get; set; }
        public string NazivGalerije { get; set; }
        public string PutanjaDoSlike { get; set; }
        public string Korisnik { get; set; }
        public Nullable<System.DateTime> DatumPostavljanja { get; set; }
        public Nullable<System.DateTime> DatumIzmene { get; set; }
    }
}
