//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slike
    {
        public int IdSlike { get; set; }
        public string NazivSlike { get; set; }
        public string PutanjaDoSlike { get; set; }
        public int IdGalerije { get; set; }
        public System.DateTime DatumPostavljanja { get; set; }
        public string Korisnik { get; set; }
        public System.DateTime DatumIzmene { get; set; }
    }
}
