//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavke
    {
        public int Id_stavke { get; set; }
        public string odgovor { get; set; }
        public int broj_glasova { get; set; }
        public int id_ankete { get; set; }
    
        public virtual ankete ankete { get; set; }
    }
}
