//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StranaKontakt
    {
        public int IdStraneKontakt { get; set; }
        public string NaslovStraneKontakt { get; set; }
        public string TekstStraneKontakt { get; set; }
        public string Bioskopi { get; set; }
        public string Korisnik { get; set; }
        public System.DateTime DatumPostavljanja { get; set; }
        public System.DateTime DatumIzmene { get; set; }
        public string NazivStraneKontakt { get; set; }
        public Nullable<int> StatusStraneKontakt { get; set; }
    }
}
