//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilankovDeo.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zanrovi
    {
        public int IdZanra { get; set; }
        public string NazivZanra { get; set; }
    }
}
